export const UPLOAD_HOT_REQUEST = 'UPLOAD_HOT_REQUEST'
export const UPLOAD_HOT_SUCCESS = 'UPLOAD_HOT_SUCCESS'
export const UPLOAD_HOT_FAIL = 'UPLOAD_HOT_FAIL'

export const FETCH_HOTS_REQUEST = 'FETCH_HOTS_REQUEST'
export const FETCH_HOTS_SUCCESS = 'FETCH_HOTS_SUCCESS'
export const FETCH_HOTS_FAIL = 'FETCH_HOTS_FAIL'