export const UPLOAD_PHOTO_REQUEST = 'UPLOAD_PHOTO_REQUEST'
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS'
export const UPLOAD_PHOTO_FAIL = 'UPLOAD_PHOTO_FAIL'

export const DELETE_ALL_PHOTOS = 'DELETE_ALL_PHOTOS'
export const DELETE_PHOTO = 'DELETE_PHOTO'