export const UPLOAD_FEEDBACK_REQUEST = 'UPLOAD_FEEDBACK_REQUEST'
export const UPLOAD_FEEDBACK_SUCCESS = 'UPLOAD_FEEDBACK_SUCCESS'
export const UPLOAD_FEEDBACK_FAIL = 'UPLOAD_FEEDBACK_FAIL'

export const FETCH_FEEDBACKS_REQUEST = 'FETCH_FEEDBACKS_REQUEST'
export const FETCH_FEEDBACKS_SUCCESS = 'FETCH_FEEDBACKS_SUCCESS'
export const FETCH_FEEDBACKS_FAIL = 'FETCH_FEEDBACKS_FAIL'