export const UPLOAD_SLIDE_REQUEST = 'UPLOAD_SLIDE_REQUEST'
export const UPLOAD_SLIDE_SUCCESS = 'UPLOAD_SLIDE_SUCCESS'
export const UPLOAD_SLIDE_FAIL = 'UPLOAD_SLIDE_FAIL'

export const FETCH_SLIDES_REQUEST = 'FETCH_SLIDES_REQUEST'
export const FETCH_SLIDES_SUCCESS = 'FETCH_SLIDES_SUCCESS'
export const FETCH_SLIDES_FAIL = 'FETCH_SLIDES_FAIL'