export const FETCH_CALLBACKS_REQUEST = 'FETCH_CALLBACKS_REQUEST'
export const FETCH_CALLBACKS_SUCCESS = 'FETCH_CALLBACKS_SUCCESS'
export const FETCH_CALLBACKS_FAIL = 'FETCH_CALLBACKS_FAIL'

export const READ_CALLBACK_REQUEST = 'READ_CALLBACK_REQUEST'
export const READ_CALLBACK_SUCCESS = 'READ_CALLBACK_SUCCESS'
export const READ_CALLBACK_FAIL = 'READ_CALLBACK_FAIL'

export const DELETE_CALLBACK_REQUEST = 'DELETE_CALLBACK_REQUEST'
export const DELETE_CALLBACK_SUCCESS = 'DELETE_CALLBACK_SUCCESS'
export const DELETE_CALLBACK_FAIL = 'DELETE_CALLBACK_FAIL'

export const CREATE_CALLBACK_REQUEST = 'CREATE_CALLBACK_REQUEST'
export const CREATE_CALLBACK_SUCCESS = 'CREATE_CALLBACK_SUCCESS'
export const CREATE_CALLBACK_FAIL = 'CREATE_CALLBACK_FAIL'